### ISSUE TITLE
Docs up to date?

### ISSUE THREAD

**Issue by gsingers** [buzzsprout/buzzsprout-api#11]
Hi, 

I'm trying to get episode creation working.  I am POSTing the example given in the docs and all I get back is a 200 OK with a list of all episodes.  

Here's what I'm sending: 
`curl --location --request POST 'https://buzzsprout.com/api/XXXXXXX/episodes.json?api_token=XXXXX' \
--header 'Content-Type: application/json' \
--data-raw '{
  "title":"Too many or too few?",
  "description":"",
  "summary":"",
  "artist":"Muffin Man",
  "tags":"",
  "published_at":"2019-09-12T03:00:00.000-04:00",
  "duration":23462,
  "hq":false,
  "guid":"Buzzsprout788880",
  "inactive_at":null,
  "episode_number":400,
  "season_number":5,
  "explicit":true,
  "private":true,
  "email_user_after_audio_processed": true,
  "audio_url": "https://www.google.com/my_audio_file.mp4",
  "artwork_url": "https://www.google.com/my_artwork_file.jpeg"
}'`

Note, I've tried sending Auth headers, too, but that seems to not work, at least when GETting.

**Comment by johnloringpollard** [comment]
When I try that command with my credentialsI get 17 errors. 

```
Bad credentialscurl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL

[1/17]:  "title":"Too many or too few?" --> <stdout>
--_curl_-- "title":"Too many or too few?"
curl: (3) URL using bad/illegal format or missing URL

[2/17]:  "description":"" --> <stdout>
--_curl_-- "description":""
curl: (3) URL using bad/illegal format or missing URL
... 
```

When I put the command all on one line I get back `{"audio_url":["is not reachable"],"artwork_url":["is not reachable"]}`. Which looks like the correct response. 

Can you try reformatting your CURL request?

**Comment by gsingers** [comment]
Sorry, that was the code generated by Postman.  I wasn't actually running cURL.  I've also tried running the Postman examples (substituting in the correct URLs) and that doesn't work either.

**Comment by johnloringpollard** [comment]
I just test this and it works. If you would like you can send me your postman request or the full actual CURL request. I'm john at buzzsprout.com.

  `curl "https://www.buzzsprout.com/api/477406/episodes.json?api_token=mytoken"`

**Comment by KnappSas** [comment]
Hey,

Similar question: 
When I do the Sample GET with
 `curl -v -H "Authorization: Token token=XXXXX" https://www.buzzsprout.com/api/XXXXXXX/episodes.json`

I simply get a 404 status code for HTTP/2. What could I do wrong here?

**Comment by tomrossi7** [comment]
A `404 Not Found` would point to a URL that points to something that doesn't exist. I would verify your credentials. Make sure the token has to have permission for the corresponding podcast_id. Feel free to email support with details.
