### ISSUE TITLE
Description property taking longer than others to be posted

### ISSUE THREAD

**Issue by emanuallan** [buzzsprout/buzzsprout-api#15]
Hello, 

I've noticed recently that the API doesn't respond with a description for a good bit with new episodes. I noticed it occur twice now, where every other episode loads the description but the newer episode (usually the day it is posted) is missing its description. Nonetheless, it does appear after like a day or so of being up. Not sure if this was known or not but just wanted to report it.

**Comment by johnloringpollard** [comment]
That is strange. The description field should be handled just like any other field and should show up immediately. 

So you create a new episode with the API, you include a description, but the response has the description field as null, you do a GET show request on the episode and it is still null, and not until a day or two later do you see the description field populated?

**Comment by emanuallan** [comment]
Hey sorry for the long turn around time, have had to work on other things. Let me see if I can catch it again and come back with more detail. I appreciate the patience.

**Comment by emanuallan** [comment]
I haven't noticed it happen recently, maybe it was just a hiccup. Going to go ahead and close this issue. If it happens I'll be sure to use this thread again. Much thanks!
