### ISSUE TITLE
Get duration via API or Embed

### ISSUE THREAD

**Issue by duynguyen145-dev** [buzzsprout/buzzsprout-api#16]
Hi all,
 How get the duration of video/media via APIs or Embed?

**Comment by tomrossi7** [comment]
You can get the duration from the [episode endpoint](https://github.com/buzzsprout/buzzsprout-api/blob/master/sections/episodes.md) in the API or you can read it within the RSS feed.

**Comment by duynguyen145-dev** [comment]
@tomrossi7 Thanks for your information, if using the API will return all the episodes for a podcast, You think to have any performance issue?
Do you know have any API  get an episode by episode_id?
