### ISSUE TITLE
get all list of podcast

### ISSUE THREAD

**Issue by moxspoy** [buzzsprout/buzzsprout-api#17]
i have list of podcast like this

![image](https://user-images.githubusercontent.com/17137806/92343567-46dd1c80-f0ee-11ea-9c9a-92f35e2a273d.png)

is there a way to get all list of podcast (i want to get list of podcast id) so that i can make request to get all episodes based on podcast id ?

**Comment by johnloringpollard** [comment]
Yes you should be able to call `/api/podcasts` to get a list of all the podcasts. Let me know if that works for you!

**Comment by moxspoy** [comment]
Thank you @johnloringpollard , it works. Why this endpoint not exist in the documentation ? It might be useful to update the docs.
