### ISSUE TITLE
Upload but not publish an episode

### ISSUE THREAD

**Issue by TechnoPorg** [buzzsprout/buzzsprout-api#18]
Hello. I am working on a project that uses the Buzzsprout API, and I would like to be able to upload an episode without publishing it. I assume it has something to do with the private or published-at values, but I would appreciate further clarification. I don't mean to cause offense, but the documentation about the different values in episodes.json feels rather incomplete. Thank you in advance!

**Comment by johnloringpollard** [comment]
If an episode is set to private, it won't be public regardless of the published_at date. If an episode has private set to false, it will be public only if published_at is in the past. Does that help?

**Comment by TechnoPorg** [comment]
Yes, that's just the information I needed. Thank you very much.
