### ISSUE TITLE
Weird duration value

### ISSUE THREAD

**Issue by baleo-it** [Buzzsprout/buzzsprout-api#2]
Hi,
Thanks for your API!

We are working on our website podcast, but we dont understand how to use the duration value from your API. 

For example, with our test episode that is 20min57 long, your API gives us a duration value of 1257.

How do we need to handle this value?

**Comment by baleo-it** [comment]
Nevermind, duration is in seconds. Why not use milliseconds as most of APIs are using?

**Comment by tomrossi7** [comment]
@baleo-it I'm glad you figured it out! Buzzsprout rounds to the second, so thats why we return seconds.

**Comment by baleo-it** [comment]
Ok, thanks for your quick answer!
