### ISSUE TITLE
Need endpoint to access transcript

### ISSUE THREAD

**Issue by johnfyoung** [buzzsprout/buzzsprout-api#21]
The current API doesn't provide access to transcripts. On our site, we want to sync the transcript to playback. Keeping all of the podcast assets on Buzzsprout would be preferred to keeping the transcript in multiple locations.

**Comment by tomrossi7** [comment]
No need to use the API. Check out your RSS feed and you'll see the links to various formats for your transcripts. Check it out and let us know what you think!

**Comment by amargosavi** [comment]
I need to access the transcript in the REST API response. Currently, I am unable to find any linked for a transcript or any RSS feed to access the transcript.

Response is shared below.

    {
        "id": 7423423485,
        "title": "Testing PODCAST",
        "audio_url": "https://www.buzzsprout.com/14dsfsdf58/7dsfs785-testing-podcast.mp3",
        "artwork_url": "https://storage.buzzsprout.com/variants/xrm3vuookd4ka2fdsfwwmrbfqciinx/sdfdsb17bbdfsdfsdfsd148cafbb129f58a3c81282007c6fe24ff2.jpg",
        "description": "",
        "summary": "",
        "artist": "Name of artist",
        "tags": "",
        "published_at": "2021-02-05T01:00:00.000-05:00",
        "duration": 618,
        "hq": false,
        "magic_mastering": false,
        "guid": "Buzzsprout-768dsd8785",
        "inactive_at": null,
        "episode_number": null,
        "season_number": null,
        "explicit": false,
        "private": false,
        "total_plays": 0
    }

**Comment by danieltott** [comment]
It would be really great to have access to the links that are in the RSS feed for individual episodes. Otherwise, to get the transcript url for instance, we need to pull down the entire RSS feed, parse the whole thing, and filter it on the episode ID to get the transcript.

**Comment by tomrossi7** [comment]
Aren't you parsing the RSS feed to get the episodes? Also, the transcript URL will always follow the same RESTful format: /:podcast_id/:episode_id/transcript(.format). I hope that helps!

**Comment by danieltott** [comment]
@tomrossi7 That url structure is very helpful - thank you!

I'm not parsing the RSS feed at all at this point. My use case is a site with individual pages for episodes that we create, and at this point we're embedding the episode using buzzsprout's player. I didn't even know there were links to the transcripts in the RSS feed, so I'd been adding them by hand. But - the thing we want to avoid is parsing the entire feed on the front-end just to display one episode. There are obviously plenty of workarounds, but this is the thing I'm trying to do (and I imagine others as well). Our pod has less than 20 episodes right now so even pulling down the entire feed and parsing it isn't really that big of a deal for us at this time, but it would be nice to be able to get all of the info for just one episode in one request.
