### ISSUE TITLE
Pagination for Account Videos

### ISSUE THREAD

**Issue by atl-bcl-team** [buzzsprout/buzzsprout-api#22]
Hello! We are using the Buzzsprout API to fetch all videos right now. But as our episode list continues to grow, it seems unnecessary to load all our data at once. Are pagination queries supported with the current API? If not what is the recommended course of action?

**Comment by johnloringpollard** [comment]
How many episodes do you currently have? This or at least a limit might be something we can add.

**Comment by atl-bcl-team** [comment]
We currently have 8 but my main concern is for the future. Is it possible to add SKIP & LIMIT as query parameters? That way anyone can implement their own pagination?

**Comment by johnloringpollard** [comment]
Not currently. Let's wait until you have more then we can see if there is a performance degradation and figure out the best solution then.
