### ISSUE TITLE
Endpoint for GET'ing list of podcasts

### ISSUE THREAD

**Issue by wiktor-jurek** [buzzsprout/buzzsprout-api#25]
# Issue

To get the information behind podcast episodes, a podcast ID is required. This is trivial to get by hand, however, it cannot be done programmatically. This is an issue if we're building an implementation in which there could be multiple podacsts, and therefore multiple podcast ID's.

# Workaround

The only current workaround is to get the podcast ID manually and hardcode it within the implementation.

Currently, there is no way to GET a list of podcasts.

## Proposed Solution

Implement a get request for getting podcast information.

To return a podcasts.json as a response:

```JSON
[
  {
    "id":"xxxxxx",
    "title":"The nice podcast",
     "description":"this is the nice podcast",
     "category":"tech",
     "language":"EN-GB",
"artwork_url":"https://storage.buzzsprout.com/variants/NABbMDx7JN5bSLzLPXyj67jA/8d66eb17bb7d02ca4856ab443a78f2148cafbb129f58a3c81282007c6fe24ff2",
    "website_url":"https://example.com",
    "episodeCount":5,
    "description":"",
    "total_plays":150,
    "directories": [
        {"spotify":{"directory_link":"..." },
         } ]
  },
```

**Comment by johnloringpollard** [comment]
You should be able to call /api/podcasts to get a list of all the podcasts. Let me know if that works for you!

**Comment by wiktor-jurek** [comment]
That works - thank you!
