### ISSUE TITLE
Bad credentials when passing token to example URL

### ISSUE THREAD

**Issue by DoubleF3lix** [buzzsprout/buzzsprout-api#32]
I'm trying to use Postman to test things, and I've made an account and got my API token, but when I pass it to `http://buzzsprout.com/api/2/episodes.json?token=TOKEN`, it gives me a 401 error with bad credentials. What am I doing wrong?

**Comment by DoubleF3lix** [comment]
Nevermind, apparently you can only use the API for your own podcasts.

**Comment by rsd-earl** [comment]
i'm getting this error while getting my own podcasts...

**Comment by DoubleF3lix** [comment]
The only advice I could give would be to double check your token is formatted correctly in the headers.
