### ISSUE TITLE
Cors Issue working locally and bad credentials when using postman or pasting the url to browser

### ISSUE THREAD

**Issue by rsd-earl** [buzzsprout/buzzsprout-api#33]
i'm currently making a script that would get all the episodes and would display it but when i tried doing so i'm getting ``CORS Issues``.
![Screenshot-1](https://user-images.githubusercontent.com/106730433/211456163-e5977144-d9e4-4550-a481-9646d679ba0b.png)

but when i try using postman i'm getting ``bad credentials`` same with pasting the url to browser.
![Screenshot from 2023-01-10 11-29-33](https://user-images.githubusercontent.com/106730433/211456436-cb06d9f9-759c-41e5-afec-81f42cab2c17.png)
![Screenshot from 2023-01-10 11-36-06](https://user-images.githubusercontent.com/106730433/211456450-4f4cf01c-06b6-4b56-88d3-3bf1e0f0a3f9.png)

**Comment by eric-hansen** [comment]
Based on your screenshots you're sending an `Authorization` header in Postman, but passing it via URI in the browser.  Why not try the same method both ways to see if the outcome is the same?

**Comment by johnloringpollard** [comment]
Send the param as `api_token` instead of `token`. Also if you send the token as a param you do not need the authorization header.

**Comment by rsd-earl** [comment]
> Based on your screenshots you're sending an `Authorization` header in Postman, but passing it via URI in the browser. Why not try the same method both ways to see if the outcome is the same?

I have tried this locally sending a request to episodes.json with the Authorization header and it gives me CORS.

I'll try both today.

**Comment by rsd-earl** [comment]
@johnloringpollard okay the api_token works, but gives me CORS issue when putting it in the script that I'm making

**Comment by rsd-earl** [comment]
@johnloringpollard for reference here's the code
![Screenshot-4](https://user-images.githubusercontent.com/106730433/211705771-e2e394fa-82ff-413a-b3b9-dc62f7ab16b7.png)

**Comment by rsd-earl** [comment]
@johnloringpollard for reference here's the code
![Screenshot-4](https://user-images.githubusercontent.com/106730433/211705903-7de133e8-2811-4e2b-8aac-04e7aedc74f7.png)

**Comment by johnloringpollard** [comment]
What happens if you run that code in the console at stackoverflow or buzzsprout.com? It works for me there which makes me wonder if theres something blocking from visual studio.

**Comment by rsd-earl** [comment]
@johnloringpollard any comment on this ?

**Comment by johnloringpollard** [comment]
I believe the issue is that you need to use the full domain. https://www.buzzsprout.com You are not using the www. portion.

**Comment by rsd-earl** [comment]
thank you @johnloringpollard didn't think that would be an issue, but it seems like, I was wrong.
