### ISSUE TITLE
Can not access `artwork_url`

### ISSUE THREAD

**Issue by longht021189** [buzzsprout/buzzsprout-api#36]
Hi,
Today, we can not access `artwork_url` content from our site.
Yesterday, It worked

Ex: `https://storage.buzzsprout.com/variants/7kon9841dpy4ggc6ximnbqiiafwe/0f95c46b012ee16829275052a5437910393899d65a5a9fc329ee783c2bb4e05c.jpeg`

Thanks.

**Comment by johnloringpollard** [comment]
Can you tell me the podcast name or RSS feed URL?

**Comment by tomrossi7** [comment]
All fixed!
