### ISSUE TITLE
Examples directory

### ISSUE THREAD

**Issue by chancestrickland** [Buzzsprout/buzzsprout-api#4]
Thanks so much for releasing an API. Just getting around to rebooting my podcast and this is going to be a huge help for the new site!

Proposing a slight enhancement to add an examples directory to the documentation with some other implementations. I created a quick plugin for Gatsby.js that might be useful for some examples using JS/Node. https://github.com/chancestrickland/gatsby-source-buzzsprout

Happy to throw up a PR in the next few days myself if you're open to collaborating!

**Comment by tomrossi7** [comment]
We would love contributions from the Buzzsprout community! Thanks @chancestrickland!
