### ISSUE TITLE
How to capture play count when loading the audio_url for an episode?

### ISSUE THREAD

**Issue by eric-hansen** [buzzsprout/buzzsprout-api#40]
The availability for the Buzzsprout player itself is not compact enough for what I'm trying to accomplish (see screenshot for an idea).

So what I plan on doing is fetching the audio URL and playing it through an `<audio>` element on the page as shown.

There's previous issues filed where it's mentioned the total_plays prop is based on the User Agent and play time of at least 60 seconds when the logs are scrapped.

How does the User Agent play into this exactly (so I can track unique plays)?

![image](https://github.com/buzzsprout/buzzsprout-api/assets/8271207/593bacc2-f009-4e37-b8b8-d2ba37182e03)

**Comment by tomrossi7** [comment]
Hey @eric-hansen! The user-agent will be the web browser that plays the episode. Does that make sense?

**Comment by eric-hansen** [comment]
So I just need to pass the user agent of the listener when fetching the
audio file?

**Comment by tomrossi7** [comment]
When the browser makes the request to the URL provided in the Audio tag, it passes the user-agent like it would for any other web page. Does that make sense?

**Comment by tomrossi7** [comment]
Its not a requirement, it just won't consider it a play if they don't download at least 60 seconds of data. Be sure that you do not automatically download the full episodes. This will inflate your stats and make them meaningless. I hope that makes sense! Good luck!
