### ISSUE TITLE
Return the Transcript in GET

### ISSUE THREAD

**Issue by justingrammens** [buzzsprout/buzzsprout-api#46]
Greetings! Thank you for creating this API to allow me to programmatically get the content from my podcast. I'm curious if might be possible to return the transcript of each episode? There's just so much content in there that would be extremely useful for me to have access to.

**Comment by tomrossi7** [comment]
You can retrieve your transcript from the predictable URL that is https://www.buzzsprout.com/:podcast_id/:episode_id/transcript(.srt|.srt). You can see the URLs in your RSS feed as well. I hope that helps!

**Comment by justingrammens** [comment]
Thank you for the quick reply! I did not see this in the API docs. One follow-up question.

As a specific example. Calling the HTML version works, ie:
https://www.buzzsprout.com/1101152/11700470/transcript.html

But, requesting the .json version, ie:
https://www.buzzsprout.com/1101152/11700470/transcript.json
with "Content-Type:application/json" in the header gives me a 404 in Postman. Is there something else I'm missing?

**Comment by tomrossi7** [comment]
That means that whatever the source of the transcript, it did not support JSON.

**Comment by justingrammens** [comment]
Gotcha. Thank you for your help. Much appreciated!

**Comment by tomrossi7** [comment]
No problem! Don't hesitate to reach out!
